version: '3.8'
services:
    master:
      build:
        context: ./master
        dockerfile: Dockerfile
#      image: ${IMAGETAG:-redis:latest}
      image: redis-master:latest
      container_name: redis-master
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data/master:${REDIS_DATA_DIR}
      env_file:
        - redis.env
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}
    #  command: redis-server /var/redis/redis.conf

    sentinel-M:
      build:
        context: ./sentinel
        dockerfile: Dockerfile
#      image: ${IMAGETAG:-redis:latest}
      image: redis-sentinel:latest
      container_name: redis-sentinel-M
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data/sentinel:${REDIS_DATA_DIR}
      env_file:
        - redis.env
      depends_on:
        - master
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}
        SENTINEL_PORT: 26379
        SENTINEL_QUORUM: 2
        SENTINEL_DOWN_AFTER: 5000
        SENTINEL_FAILOVER_TIMEOUT: 8000
    #  command: redis-server /var/redis/redis.conf --sentinel
    
    
