version: '3.8'
services:
    master:
      build:
        context: ./master
        dockerfile: Dockerfile
      image: redis-master:latest
      container_name: redis-master
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data/master:${REDIS_DATA_DIR}
      env_file:
        _.env
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}
    #  command: redis-server /var/redis/redis.conf
    slave-1:
      build:
        context: ./slave
        dockerfile: Dockerfile
      image: redis-slave:latest
      container_name: redis-slave-1
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data/slave1:${REDIS_DATA_DIR}
      env_file:
        _.env
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:- 6379}
        SLAVE_IP: 127.0.0.1
        SLAVE_PORT: 6380
    slave-2:
      build:
        context: ./slave
        dockerfile: Dockerfile
      image: redis-slave:latest
      container_name: redis-slave-2
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data/slave2:${REDIS_DATA_DIR}
      env_file:
        _.env
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:- 6379}
        SLAVE_IP: 127.0.0.1
        SLAVE_PORT: 6381   
    
    sentinel-1:
      build:
        context: ./sentinel
        dockerfile: Dockerfile
      image: redis-sentinel:latest
      container_name: redis-sentinel-1
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data/sentinel1:${REDIS_DATA_DIR}
      env_file:
        _.env
      depends_on:
        - master
        - slave-1
        - slave-2
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}
        SENTINEL_PORT: 26379
        SENTINEL_QUORUM: 2
        SENTINEL_DOWN_AFTER: 5000
        SENTINEL_FAILOVER_TIMEOUT: 8000
        
    sentinel-2:
      build:
        context: ./sentinel
        dockerfile: Dockerfile
      image: redis-sentinel:latest
      container_name: redis-sentinel-2
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data/sentinel2:${REDIS_DATA_DIR}
      env_file:
        _.env
      depends_on:
        - master
        - slave-1
        - slave-2
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}
        SENTINEL_PORT: 26380
        SENTINEL_QUORUM: 2
        SENTINEL_DOWN_AFTER: 5000
        SENTINEL_FAILOVER_TIMEOUT: 8000
        
    sentinel-3:
      build:
        context: ./sentinel
        dockerfile: Dockerfile
      image: redis-sentinel:latest
      container_name: redis-sentinel-3
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data/sentinel3:${REDIS_DATA_DIR}
      env_file:
        _.env
      depends_on:
        - master
        - slave-1
        - slave-2
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}
        SENTINEL_PORT: 26381
        SENTINEL_QUORUM: 2
        SENTINEL_DOWN_AFTER: 5000
        SENTINEL_FAILOVER_TIMEOUT: 8000
    
    
