version: '3.8'
services:
    master:
      build:
        context: .
        dockerfile: Dockerfile
#      image: ${IMAGETAG:-redis:latest}
      image: redis-sentinel:latest
      container_name: redis-sentinel
      network_mode: host
      restart: always
      privileged: true
      volumes:
        - ./data:${REDIS_DATA_DIR}
#      env_file:
#        .env
      environment:
        REDIS_PWD: ${REDIS_PWD:-123456}
        REDIS_HOST_IP: ${REDIS_HOST_IP:-127.0.0.1}
        REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}
        SENTINEL_QUORUM: ${SENTINEL_QUORUM:-2}
        SENTINEL_DOWN_AFTER: ${SENTINEL_DOWN_AFTER:-5000}
        SENTINEL_FAILOVER_TIMEOUT: ${SENTINEL_FAILOVER_TIMEOUT:-5000}
#      command: redis-server /var/redis/redis.conf --sentinel
    
    
